spring:
  application:
    name: backend-with-grpc-client

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9000'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext